### ISSUE TITLE
Homework js2 week 3

### ISSUE THREAD

**Issue by mogenshoj** [cecastosic/hyf-homework#1]
Don't really have a lot of comments for this. It looks very good. Keep writing your code this clean, it's very easy to read! Good job 👍 

**Warmup**
Very clean code and easy to read, nice to see!
I like the jokes 💃 

**Game**
Cool game, nice confetti implementation 👍 

**hyfBay**
Also good 👍

**Comment by cecastosic** [comment]
Thank you for your feedback!
