### ISSUE TITLE
JS2 Week 2 Feedback

### ISSUE THREAD

**Issue by orhantoy** [cecastosic/hyf-homework#2]
@cecastosic :v:

## Warmup array exercises / Doubling of number

Good job on this exercise. A minor way you could improve and simplify the implementation would be to remove ` ? true : false` from this line

https://github.com/cecastosic/hyf-homework/blob/867d90e11f525291df34df39ccaf0488b8c13c55/javascript/javascript2/week2/doubling.js#L14

This is because `number % 2 !== 0` already returns true/false. Let me know if I need to elaborate on this.

## Warmup array exercises / Working with movies

- Exercise 1, 2 and 5: Nice work here. Similar to my comment from the doubling the number exercise, you can simplify these by removing ` ? true : false`.
  https://github.com/cecastosic/hyf-homework/blob/867d90e11f525291df34df39ccaf0488b8c13c55/javascript/javascript2/week2/main-movies.js#L5
  https://github.com/cecastosic/hyf-homework/blob/867d90e11f525291df34df39ccaf0488b8c13c55/javascript/javascript2/week2/main-movies.js#L10
  https://github.com/cecastosic/hyf-homework/blob/867d90e11f525291df34df39ccaf0488b8c13c55/javascript/javascript2/week2/main-movies.js#L33
- Exercise 3: Awesome use of `reduce` here 🎉 The part with `sum += 1` should probably have been `sum + 1` but both seem to work in the end. This is because with `reduce` the return value from the previous iteration will be the accumulator (`sum` variable in this case) on the following iteration.
- Exercise 4: This is close to being the right solution. Instead of modifying `movies` you should instead create a new array as stated in the exercise. Hint: try using `map`.
  https://github.com/cecastosic/hyf-homework/blob/867d90e11f525291df34df39ccaf0488b8c13c55/javascript/javascript2/week2/main-movies.js#L17-L28
- Exercise 6: Nice job on this exercise. One minor thing to improve is that currently if a movie title includes "Surfers" then it would also count that as match. This is not a big deal though IMO 👍 
  https://github.com/cecastosic/hyf-homework/blob/867d90e11f525291df34df39ccaf0488b8c13c55/javascript/javascript2/week2/main-movies.js#L40
- Exercise 7: Nice work on this exercise as well 👍 A way to simplify this a bit could be by having a separate `containsDuplicateWords` function and then using that in a `filter`.
  https://github.com/cecastosic/hyf-homework/blob/867d90e11f525291df34df39ccaf0488b8c13c55/javascript/javascript2/week2/main-movies.js#L44-L53
- Exercise 8: Great to see that you also tackled the optional exercises! 💪 One thing I would have done differently would have been to have `duplicatedWords` be an object instead of an array. You would then use the words as keys to the object and increment a counter every time you see that word. At the end you would then do `duplicatedWords.values.sort`.
- Exercise 9: ✅ 
- Exercise 10: ✅ 

If you have questions, please feel free to ask them in here. Again, great work! 💯 

## hyfBay - get the okay'est products here - continued

Great work here, nice to see that you've tackled all the exercises.

Feedback:
- The search could be slightly improved so words didn't have match exactly in the name of the product.
- You could avoid the global variable `searched` and also simplify this part
  https://github.com/cecastosic/hyf-homework/blob/1808d6d9a26472858c76a6d5814c56f1d859cf1e/javascript/javascript2/week2/hyf-bay/main.js#L67-L74
  by instead always applying a filter. For the case of an empty search string you would then have a `filter` function which always returns `true`.
- `productsSearchCountry` could be simplified a bit by using [`includes`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes).
- Again, awesome work :tada: 👍
  To take it to next level I would recommend using a linter to format the code a bit nicer and more consistently. I also see you use 4 spaces for indentation and I think the common JS approach is 2 spaces - this is not a big deal and mainly a matter of preference.

**Comment by orhantoy** [comment]
@cecastosic Updated with hyfBay feedback :v:

**Comment by cecastosic** [comment]
Thanks for your feedback!

**Comment by orhantoy** [comment]
@cecastosic Good job on addressing the feedback :v: Exercise 4 (Movies, rating) is still not entirely correct:

https://github.com/cecastosic/hyf-homework/blob/543851a052269102fea7d8d3679d110e13b0cc48/javascript/javascript2/week2/main-movies.js#L17-L29

There are 2 issues:
1. You `return movies` but that will create an array of arrays which is not what you want. Try to debug this a bit and I think you will solve it.
2. By setting `movie.tag` you actually modify the original objects from `movies`. Instead try finding out how you can copy an object.

Once you fix exercise 4 I'll mark the homework as approved.

**Comment by cecastosic** [comment]
@orhantoy Thanks again for your feedback!
1. is fixed now with 'return movie'
2. I tried several things but the only thing that works (ie not changing original movies object) is 'JSON.parse(JSON.stringify(obj))' - any thoughts about this?

**Comment by orhantoy** [comment]
Awesome!

2. Your approach by converting to JSON and then parsing should also work but is probably less performant than for instance doing something like this

```js
const newMovies = movies.map(movie => {
  let tag;

  if (movie.rating >= 7) {
    tag = "Good";
  } else if (movie.rating >= 4 && movie.rating < 7) {
    tag = "Average";
  } else {
    tag = "Bad";
  }

  return Object.assign({ tag: tag }, movie);
});
```

**Comment by orhantoy** [comment]
Closing this issue now as you've completed the exercise fully 🎉
